### ISSUE TITLE
Create additional whitelist that enables free minting

### ISSUE THREAD

**Issue by wgmi-rambo** [wgmi-rambo/nft-contract#12]
This whitelist, `freeMintAddresses`, will contain the addresses of contributors to this project.
If an address is in the `freeMintAddresses` list, then the cost of minting should be free for their first mint only (by checking `freeMintAddressesMintedBalance`).

This check should be independent of `onlyWhitelisted`'s value; aka, we should always check if someone is in this whitelist.

The following variables need to be added:

- address[] public freeMintAddresses;
- mapping(address => uint256) public freeMintAddressesMintedBalance;

The following method needs to be added:

```solidity
function setFreeMintAddresses(address[] calldata _users) public onlyCommunityOwner {
    delete freeMintAddresses;
    freeMintAddresses = _users;
}
```

**Comment by wgmi-rambo** [comment]
This list shouldn't include \@Guille23 since his minting logic will be seperate

**Comment by AlliedToasters** [comment]
Should be sorted by pr-20 .. I accidentally merged it but reverted the merge
