### ISSUE TITLE
Limit minting of token #888 to @Guille23

### ISSUE THREAD

**Issue by wgmi-rambo** [wgmi-rambo/nft-contract#13]
This NFTs artist, known as @Guille23 on the $WGMI Discord, should be the only user able to mint token \#888.

We should do this by:
Adding a variable storing his address:
```solidity
address public guille23Address = 0x12345
```

**Note that this hard-coded address must contain a checksum.** Use this website to format the address correctly: [https://ethsum.netlify.app/](https://ethsum.netlify.app/).

Then, we need to set `maxSupply` to 887.

Then, create a new public method for guille23 to mint:

```solidity
function guille23Mint() public payable {
    require(!paused, "the contract is paused");
    require(msg.sender == guille23Address, "guille23Address is not the caller")
    uint256 supply = totalSupply();
    require(supply == 887, "Only token #888 can be minted");

    addressMintedBalance[msg.sender]++;
    _safeMint(msg.sender, 888);
}
```

**Comment by AlliedToasters** [comment]
Attempted solution [pr-15](https://github.com/wgmi-rambo/nft-contract/pull/15)
