### ISSUE TITLE
Update usage of onlyCommunityOwner and implementation of withdraw()

### ISSUE THREAD

**Issue by wgmi-rambo** [wgmi-rambo/nft-contract#21]
Current usage is:

- setNftPerAddressLimit
- setWhitelistNftPerAddressLimit
- setCost
- setBaseURI
- setBaseExtension
- setNotRevealedURI
- whitelistUsers
- withdraw

However, to reduce the cost of calling these methods, in terms of gas and coordination-efforts, we should only apply onlyCommunityOwner to methods with a large impact.

As proposed by members of the WGMI discord, we should only apply onlyCommunityOwner to the following methods:

- withdraw
- end presale

However, we can also remove onlyCommunityOwner from `withdraw` if we update the withdraw function to only withdraw to the community wallet. Implemented this way, any person in the world could call withdraw (using their own gas), and the communityOwner would receive the contract's balance.

**Comment by AlliedToasters** [comment]
In discord, we've decided to trust the contract owner with all operations except setWithdrawAddress(), setDevAddresses(), and setGuilleAddress(); contract is coded to only withdraw to withdrawAddress. Changes and tests in [pr-22](https://github.com/wgmi-rambo/nft-contract/pull/22)
